# Generated by Django 5.1.2 on 2024-11-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocal_app', '0004_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
