# Generated by Django 5.1.2 on 2024-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal_app', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('phone', models.CharField(default='', max_length=12)),
                ('address', models.TextField()),
                ('profile_pic', models.ImageField(default='', upload_to='test_app/profile_pic')),
            ],
        ),
    ]
