# Generated by Django 5.0 on 2024-11-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal_app', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
